### ISSUE TITLE
HTTPX timeouts

### ISSUE THREAD

**Issue by azmeuk** [migraf/fhir-kindling#111]
**Describe the bug**
Since 0.9 I encounter read timeouts with httpx every time I read a large quantity of objects from an API.
0.8 was OK

I am not sure what is going on. I suppose the switch to httpx may have caused this?

[The httpx timeout doc](https://www.python-httpx.org/quickstart/#timeouts)

```python
Traceback (most recent call last):
  File "/path/to/env/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/path/to/env/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib/python3.10/ssl.py", line 1259, in recv
    return self.read(buflen)
  File "/usr/lib/python3.10/ssl.py", line 1132, in read
    return self._sslobj.read(len)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/env/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/path/to/env/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/path/to/env/httpcore/_sync/connection_pool.py", line 252, in handle_request
    raise exc
  File "/path/to/env/httpcore/_sync/connection_pool.py", line 236, in handle_request
    response = connection.handle_request(request)
  File "/path/to/env/httpcore/_sync/socks_proxy.py", line 294, in handle_request
    return self._connection.handle_request(request)
  File "/path/to/env/httpcore/_sync/http11.py", line 112, in handle_request
    raise exc
  File "/path/to/env/httpcore/_sync/http11.py", line 91, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/path/to/env/httpcore/_sync/http11.py", line 155, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/path/to/env/httpcore/_sync/http11.py", line 191, in _receive_event
    data = self._network_stream.read(
  File "/path/to/env/httpcore/backends/sync.py", line 24, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/path/to/env/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
  File "/path/to/srv/command.py", line 80, in preload_entities
    json.dump(query.all().response, fd)
  File "/path/to/env/fhir_kindling/fhir_query/fhir_query.py", line 351, in all
    return self._execute_query(page_callback=page_callback, count=count)
  File "/path/to/env/fhir_kindling/fhir_query/fhir_query.py", line 401, in _execute_query
    r = client.get(self.query_url)
  File "/path/to/env/httpx/_client.py", line 1045, in get
    return self.request(
  File "/path/to/env/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/path/to/env/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/path/to/env/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/path/to/env/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/path/to/env/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/path/to/env/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/path/to/env/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out
make: *** [Makefile:169 : download-ans-practitioners-json] Erreur 1
```

**Comment by migraf** [comment]
Yes I initially had a default timeout of 60 seconds configured for the `httpx` client. This can be set when initializing the `FhirServer` instance.
```python
server = FhirServer(api_adress="...", timeout=60)
```
I have changed the default configuration to not include a timeout value.
Version `0.9.6` should be published now and contains the fix. Let me know if that solve the problem

**Comment by azmeuk** [comment]
Yep this is better. Thanks!
