### ISSUE TITLE
Validation error with address data

### ISSUE THREAD

**Issue by azmeuk** [migraf/fhir-kindling#54]
Hi. My company is part of a test phase of the French government health data public API. I encounter some minor issues whith fhir-kindling and this API that I would like to discuss here. Note that as early-adopters we have the possibility to discuss with people behind this API, so if bugs are on their side they should be reactive to fix it.

I encounter an error with a simple Organization request.

```python
>>> from fhir.resources.organization import Organization
>>> from fhir_kindling import FhirServer
>>> from fhir_kindling.fhir_query.query_parameters import QueryOperators
>>> server = FhirServer(...)
>>> query = server.query(resource=Organization).where("identifier", QueryOperators.eq, "http://finess.sante.gouv.fr%7C")
>>> resp = query.first()
>>> resp.response
{'resourceType': 'Bundle', 'id': '83b75fc6-4af1-415a-b4a9-38737f103176', 'meta': {'lastUpdated': '2022-03-04T11:04:05.751+00:00'}, 'type': 'searchset', 'total': 148226, 'link': [{'relation': 'self', 'url': 'http://demo.openfhir.annuaire.asipsante.fr:8080/fhir/Organization?_count=1&_format=json&identifier=http%3A%2F%2Ffiness.sante.gouv.fr%7C'}, {'relation': 'next', 'url': 'http://demo.openfhir.annuaire.asipsante.fr:8080/fhir?_getpages=9e26c452-1eb9-4c05-9a0b-ff07cbefcc16&_getpagesoffset=1&_count=1&_format=json&_bundletype=searchset'}], 'entry': [{'fullUrl': 'http://demo.openfhir.annuaire.asipsante.fr:8080/fhir/Organization/001-14514', 'resource': {'resourceType': 'Organization', 'id': '001-14514', 'meta': {'versionId': '0.1', 'lastUpdated': '2014-10-29T19:41:18.000+00:00', 'source': 'https://annuaire.sante.fr', 'profile': ['https://apifhir.annuaire.sante.fr/ws-sync/exposed/structuredefinition/organization-rass']}, 'language': 'fr', 'identifier': [{'use': 'official', 'type': {'coding': [{'system': 'http://interopsante.org/CodeSystem/fr-v2-0203', 'code': 'IDNST'}]}, 'system': 'urn:oid:1.2.250.1.71.4.2.2', 'value': '1010000602'}, {'use': 'official', 'type': {'coding': [{'system': 'http://interopsante.org/CodeSystem/fr-v2-0203', 'code': 'FINEJ'}]}, 'system': 'http://finess.sante.gouv.fr', 'value': '010000602'}, {'use': 'official', 'type': {'coding': [{'system': 'http://interopsante.org/CodeSystem/fr-v2-0203', 'code': 'INTRN'}]}, 'system': 'https://annuaire.sante.fr', 'value': 'F010000602'}], 'active': True, 'type': [{'coding': [{'system': 'http://interopsante.org/fhir/CodeSystem/fr-v2-3307', 'code': 'LEGAL-ENTITY'}]}, {'coding': [{'system': 'https://mos.esante.gouv.fr/NOS/TRE_R72-FinessStatutJuridique/FHIR/TRE-R72-FinessStatutJuridique', 'code': '60'}]}], 'name': 'INSTITUTION JOSEPHINE GUILLON', 'telecom': [{'system': 'phone', 'value': '0478557628', 'rank': 1}], 'address': [{'extension': [{'url': 'http://www.interopsante.org/fhir/structuredefinition/datatype/fr-address-insee-code', 'valueCode': '01249'}], 'line': [None], '_line': [{'extension': [{'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber', 'valueString': '80'}, {'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameType', 'valueString': 'AV'}, {'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameBase', 'valueString': 'JOSEPHINE GUILLON'}, {'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-postBox', 'valueString': 'BP 518'}]}], 'city': '01705 MIRIBEL CEDEX', 'postalCode': '01705'}]}}]}
>>> resp.resources
[]
```
This is surprising, as `resp.response` seems to contains correct data.

```python
>>> resp._extract_resources()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/ssd/dev/yaal/lum1/local.virtualenv/lib/python3.9/site-packages/fhir_kindling/fhir_query/query_response.py", line 190, in _extract_resources
    for entry in Bundle(**self.response).entry:
  File "/mnt/ssd/dev/yaal/lum1/local.virtualenv/lib/python3.9/site-packages/fhir/resources/fhirabstractmodel.py", line 105, in __init__
    BaseModel.__init__(__pydantic_self__, **data)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Bundle
entry -> 0 -> resource -> address -> 0 -> line -> 0
  none is not an allowed value (type=type_error.none.not_allowed)

1 validation error for Bundle
entry -> 0 -> resource -> address -> 0 -> line -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
```

So address data might be wrong? Let us check:
```python
>>> resp.response["entry"][0]["resource"]["address"][0]
{'extension': [{'url': 'http://www.interopsante.org/fhir/structuredefinition/datatype/fr-address-insee-code', 'valueCode': '01249'}], 'line': [None], '_line': [{'extension': [{'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber', 'valueString': '80'}, {'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameType', 'valueString': 'AV'}, {'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameBase', 'valueString': 'JOSEPHINE GUILLON'}, {'url': 'http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-postBox', 'valueString': 'BP 518'}]}], 'city': '01705 MIRIBEL CEDEX', 'postalCode': '01705'}
```

So `line` is `None` but the [spec](http://hl7.org/fhir/STU3/datatypes-definitions.html#Address.line) indicate it should only be a string.

Do I correctly understand the documentation and the data is wrong, or is there something to be done on the fhir-kindling side?

Thank you for your insight

**Comment by migraf** [comment]
My initial thought is that `line` parameter needs to be either a `List[str]` or `None` and in the resource you showed it is a `[None]` a list of a single `None` value.

```python
>>> [None] is None
False
```
I would say that in this case the data wrong.

**Comment by azmeuk** [comment]
Actually it seems to be valid FHIR: http://hl7.org/fhir/json.html#primitive
I guess fhir-kindling does not handle primitive values separated in two parts at the moment?

**Comment by migraf** [comment]
Yes, seems like it. I'll have a closer look, but since resource parsing is handled by [fhir.resources](https://github.com/nazrulworld/fhir.resources) library. So it'll be an issue that has to be passed on to them or one might have to make a PR.
